CREATE TABLE USERS (
ID bigint IDENTITY(1,1),
EMAIL varchar (20),
PASSWORD varchar (20),
PRIMARY KEY (ID)
)

CREATE TABLE COORDINATES  (
ID bigint IDENTITY(1,1),
LAT varchar (20),
LNG varchar (20),
DESCRIPTION varchar (50),
OBSERVATION varchar (50),
PRIMARY KEY (ID)
)

ALTER TABLE USERS ADD NEW_FIELD varchar(50) NOT NULL
ALTER TABLE COORDINATES ADD NEW_FIELD varchar(50) NOT NULL

DROP TABLE USERS
DROP TABLE COORDINATES

TRUNCATE TABLE USERS
TRUNCATE TABLE COORDINATES
